apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: docker.io/naveenmsd007/todo-ui:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-ui-service
spec:
  selector:
    app: todo-ui
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer